"""First-stage spectral anomaly detection."""

from .energy import (
    WindowData,
    detect_energy_anomalies,
    prepare_analysis_windows,
    plot_suspicious_windows,
    plot_window,
)
from .msst import (
    AnalysisPeriod,
    MSSTResult,
    analyze_msst_monitoring_data,
    analyze_msst_monitoring_period,
    analyze_msst_periods,
    analyze_stft_periods,
    msst_stft,
    plot_msst_periods,
    prepare_analysis_periods,
    prepare_monitoring_period,
    stft_only,
)
from .structure import (
    SpectralComponent,
    StructuralComparison,
    StructuralMSSTResult,
    analyze_structural_windows,
    compare_stft_msst_structure,
    compare_structural_windows,
    compute_structure_tensor,
    extract_msst_structure,
    extract_spectral_structure,
    normalize_msst_local,
    normalize_spectral_map_local,
    plot_stft_msst_comparison,
    plot_structural_window,
)

__all__ = [
    "WindowData",
    "detect_energy_anomalies",
    "prepare_analysis_windows",
    "plot_suspicious_windows",
    "plot_window",
    "AnalysisPeriod",
    "MSSTResult",
    "analyze_msst_monitoring_data",
    "analyze_msst_monitoring_period",
    "analyze_msst_periods",
    "analyze_stft_periods",
    "msst_stft",
    "plot_msst_periods",
    "prepare_analysis_periods",
    "prepare_monitoring_period",
    "stft_only",
    "SpectralComponent",
    "StructuralComparison",
    "StructuralMSSTResult",
    "analyze_structural_windows",
    "compare_stft_msst_structure",
    "compare_structural_windows",
    "compute_structure_tensor",
    "extract_msst_structure",
    "extract_spectral_structure",
    "normalize_msst_local",
    "normalize_spectral_map_local",
    "plot_stft_msst_comparison",
    "plot_structural_window",
]
